### ISSUE TITLE
Saturn wheel support

### ISSUE THREAD

**Issue by pupdeg** [sonik-br/SaturnMultiUSB#1]
Not really an issue as such, but it'd be nice to list it on the page as "not working". Tested my adapter with a 3D pad that worked perfectly, but the official wheel doesn't do anything.

**Comment by sonik-br** [comment]
Hi. I don't have an saturn wheel to test. It was really only tested with the devices that I have access. :/
But we can try to add support for it if you want.
You have any experience with arduino? Debug some code using serial port?

**Comment by pupdeg** [comment]
I'm pretty clueless when it comes to coding and arduinos in general, I had to only use port 2 because I"m using a Pro Micro without A4 and 5.  If you've got some code I can run I can give it a shot, going through all the buttons and seeing what they return. I'm guessing if I just add "#define ENABLE_SERIAL_DEBUG" to the code it'll give me a readout? After testing it a bit I realized I had to un-comment the debug stuff too, aside from the "firstnibble" one which threw up an error.

I got a response of 3-WIRE-HANDSHAKE, UNKNOWN, 640, 1360. 640 went from 628-648, while 1360 went from 1352-1368 or so, updating seemingly at random every second, with no inputs have any effect on the update rate or numbers displayed.

**Comment by sonik-br** [comment]
The serial debug is exactly what you're doing. But the code just is not ready yet for the racing wheel. That's why you're getting the 3-WIRE-HANDSHAKE, UNKNOWN.

I will take a look at the Pro Micro specs and update code for it to be compatible.
It's easy for you to test port 1 if I update the code?

**Comment by pupdeg** [comment]
I've altered the port 1 pins to be the port 2 pins and vice versa, and it works fine with the adapter set to just be 1 port. It's not really an issue, given I only needed 1 port anyway.

**Comment by sonik-br** [comment]
Hi.
I've added support for the racing wheel. Please test :)
It's on a dedicated [branch](/sonik-br/SaturnMultiUSB/tree/AddArcadeRacer).

According to the specs it will return:
* "left butterfly shifter" as DPAD UP
* "right butterfly shifter" as DPAD DOWN

Left and right movement on the wheel should map to analog and also on the DPAD. The wheel works this way to make it compatible with digital only games on saturn. I can fix this on the adapter later...

**Comment by pupdeg** [comment]
Great stuff, works perfectly. All the buttons respond as expected. The left/right digital only activates after a 15 degree angle, but I imagine that's by design, I wouldn't want it any lower anyway. Thanks for the support.

**Comment by sonik-br** [comment]
Cool!
BTW I'm making some changes to the code. It will be a lot easier to change the used arduino pins.

**Comment by sonik-br** [comment]
Hi @pupdeg ,
I've [rewritten it as a library](
https://github.com/sonik-br/SaturnLib). It's easier to define the used pins.
Also easier to customize the button mapping.
Please test it if possible. I would like to know it it works on the Pro Micro.
There's a sketch for a dual port and for a single port.

The racing wheel will not report the digital Left and Right when turning the wheel. It's an condition on the sketch file and you can comment the code block if desired.

**Comment by pupdeg** [comment]
Tested it on a pro micro with the second set of pins with the single port sketch, works perfectly with all my controllers.
